site_name: Developers
theme:
  name: material
  language: ru
  logo: assets/koshelek.svg
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
nav:
  - MkDocs Material: index.md
  - PlantUML: plantuml.md
  - OpenAPI: openapi.md
  - Версионирование: versioning.md
  - Локализация: localization.md
  - Разметка: markdown.md
  - Поиск: search.md
  - Обратная связь: feedback.md
  - Аналитика: analytics.md
  - Кастомизация: customization.md
  - Плагины: plugins.md
  - Процесс ревью: review.md
extra:
  homepage: https://koshelekapi.github.io/mkdocs-material/
  alternate:
    - name: English
    - link: /en/
    - lang: en
    - name: Русский
    - link: /ru/
    - lang: ru
plugins:
  - search
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # offical plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'png' # or "svg"
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: 'puml' # comma separated list of extensions to parse, by default every file is parsed
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml  # PlantUML server, for remote rendering other global options
      cachedir: /tmp                            # set a non-empty value to enable caching
      base_dir: .                               # where to search for diagrams to include
      format: png                               # default diagram image format
      classes: class1,class2                    # default diagram classes
      title: UML diagram                        # default title (tooltip) for diagram images
      alt: UML diagram image                    # default `alt` attribute for diagram images
      priority: 23                              # plugin priority; the higher, the sooner will be applied (default 23)