site_name: MkDocs Material
theme:
  name: material
  language: ru
  features:
    - navigation.sections
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: pink
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
nav:
  - О проекте: index.md
  - PlantUML: plantuml.md
  - OpenAPI: openapi.md
  - Версионирование: versioning.md
  - Локализация: localization.md
  - Разметка: markdown.md
  - Поиск: search.md
  - Обратная связь: feedback.md
  - Аналитика: analytics.md
  - Кастомизация: customization.md
  - Плагины: plugins.md
  - Процесс ревью: review.md
markdown_extensions:
  - attr_list
  - admonition # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/?h=markdown#admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist: # https://squidfunk.github.io/mkdocs-material/reference/lists/
      custom_checkbox: false
  - pymdownx.tabbed: # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
      alternate_style: true
  - pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  homepage: https://koshelekapi.github.io/mkdocs-material/
plugins:
  - search
  - render_swagger
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # offical plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'png' # or "svg"
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: 'puml' # comma separated list of extensions to parse, by default every file is parsed
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "ru"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      languages:
        ru:
          name: Русский
          build: true
          site_name: "MkDocs Material"
        en:
          name: English
          build: true
          site_name: "MkDocs Material (EN)"
      nav_translations:
        en:
          О проекте: About
          Версионирование: Versioning
          Локализация: Localization
          Разметка: Markdown
          Поиск: Search
          Обратная связь: Feedback
          Аналитика: Analytics
          Кастомизация: Customization
          Плагины: Plugins
          Процесс ревью: Process
