site_name: MkDocs Material
docs_dir: docs/ru-ru
site_dir: site
theme:
  name: material
  language: ru
  features:
    - navigation.sections
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: pink
      toggle:
          icon: material/toggle-switch
          name: Switch to light mode
nav:
  - О проекте: index.md
  - PlantUML: plantuml.md
  - OpenAPI: openapi/openapi.md
  - Версионирование: versioning.md
  - Локализация: localization.md
  - Разметка: markdown.md
  - Поиск: search.md
  - Обратная связь: feedback.md
  - Аналитика: analytics.md
  - Кастомизация: customization.md
  - Плагины: plugins.md
  - Процесс ревью: review.md
extra:
  homepage: https://koshelekapi.github.io/mkdocs-material/
  alternate:
    - name: English
    - link: docs/en-us/
    - lang: en
    - name: Русский
    - link: docs/ru-ru
    - lang: ru
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist: # https://squidfunk.github.io/mkdocs-material/reference/lists/
      custom_checkbox: false
  - pymdownx.tabbed: # https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#tabbed
      alternate_style: true
plugins:
  - search
  - build_plantuml:
      render: 'server' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # offical plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'png' # or "svg"
      diagram_root: 'docs/diagrams' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'src'
      input_extensions: 'puml' # comma separated list of extensions to parse, by default every file is parsed
  - render_swagger